name = "ITB Land"
author = "X341"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ff898bc4017c4d96e3f188645c9f2db8e1f9eb6df4dfc18bef1fa71f3434a10"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
