name = "ITB Land"
author = "X341"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79ab99c44ceb992280e16f7e72b5f9ef9aace55af04dc84bb284cee155e11b23"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
