name = "ITB Land"
author = "X341"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8bae154eb8f4bebd6f1343e3c3435c509ee808412fc783c79da23d143aa5e54"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
