name = "ITB Land"
author = "X341"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b0115ee5175f65cbf364a8561fa0ba8d13fc274eacc049ac072c95c4caae7b7"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"
